### ISSUE TITLE
Configuration Dialog needs Field Labels

### ISSUE THREAD

**Issue by BJReplay** [loryanstrant/EPA_AirQuality_HA#4]
![image](https://github.com/loryanstrant/EPA_AirQuality_HA/assets/37993507/19512d43-9a99-4783-aaed-d872a110897c)

I guessed that the API Key was the first field, and the Site ID was the second field, but neither order worked - both versions gave me and Unknown Error occurred.

The good news is that the integration installed as a manual install into HACS, and the release.yml workflow now works, and the HACS workflow is ignoring the brand check for the moment, too.

**Comment by loryanstrant** [comment]
Awesome. I've added the repo and installed it via HACS using the URL, all good there.

Just looking through the logs and I did notice this:
![image](https://github.com/loryanstrant/EPA_AirQuality_HA/assets/51473494/d6359a27-28cc-41c6-91fc-4f922e9f3a34)

Perhaps something left over from the copy & paste?

**Comment by loryanstrant** [comment]
Argh, I'm going around in circles a bit looking at some of the other integrations and trying to replicate bits to make it work.
And given I know nothing about Python I'm flying blind trying to figure out which example/sample/component to borrow bits of code from, and I'm mindful of not overwriting the stuff you've been doing.
If you're up for it, maybe we can have a direct chat (instead of via comments) to see how we can pick bits of this off so I'm not necessarily bumbling my way around and messing up your contribution.
My contact options are on my profile page to make it easier. :-)

**Comment by BJReplay** [comment]
> Perhaps something left over from the copy & paste?

Almost certainly.  I won't look tonight, but I will look and find it.

> If you're up for it, maybe we can have a direct chat
> My contact options are on my profile page to make it easier. :-)

Yep. For sure :)

I'm just getting through my email ahead of the work (such as it is for me) week tonight, but yep.
